/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.fatec.poo;

import javafx.application.Application;

public class App {
    public String getGreeting() {
        return "Lista de Tarefas - Start!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Application.launch(UIListaTarefas.class, args);
    }
}
